/*
 * Copyright 2018 ProximaX Limited
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * Proximax P2P Storage REST API
 * Proximax P2P Storage REST API
 *
 * OpenAPI spec version: v0.0.1
 * Contact: proximax.storage@proximax.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.proximax.xpx.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;



/**
 * MultisigInfo.
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-04-25T23:45:59.064-04:00")
public class MultisigInfo {
  
  /** The cosignatories count. */
  @SerializedName("cosignatoriesCount")
  private Integer cosignatoriesCount = null;

  /** The min cosignatories. */
  @SerializedName("minCosignatories")
  private Integer minCosignatories = null;

  /**
   * Cosignatories count.
   *
   * @param cosignatoriesCount the cosignatories count
   * @return the multisig info
   */
  public MultisigInfo cosignatoriesCount(Integer cosignatoriesCount) {
    this.cosignatoriesCount = cosignatoriesCount;
    return this;
  }

   /**
    * Get cosignatoriesCount.
    *
    * @return cosignatoriesCount
    */
  @ApiModelProperty(value = "")
  public Integer getCosignatoriesCount() {
    return cosignatoriesCount;
  }

  /**
   * Sets the cosignatories count.
   *
   * @param cosignatoriesCount the new cosignatories count
   */
  public void setCosignatoriesCount(Integer cosignatoriesCount) {
    this.cosignatoriesCount = cosignatoriesCount;
  }

  /**
   * Min cosignatories.
   *
   * @param minCosignatories the min cosignatories
   * @return the multisig info
   */
  public MultisigInfo minCosignatories(Integer minCosignatories) {
    this.minCosignatories = minCosignatories;
    return this;
  }

   /**
    * Get minCosignatories.
    *
    * @return minCosignatories
    */
  @ApiModelProperty(value = "")
  public Integer getMinCosignatories() {
    return minCosignatories;
  }

  /**
   * Sets the min cosignatories.
   *
   * @param minCosignatories the new min cosignatories
   */
  public void setMinCosignatories(Integer minCosignatories) {
    this.minCosignatories = minCosignatories;
  }


  /* (non-Javadoc)
   * @see java.lang.Object#equals(java.lang.Object)
   */
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MultisigInfo multisigInfo = (MultisigInfo) o;
    return Objects.equals(this.cosignatoriesCount, multisigInfo.cosignatoriesCount) &&
        Objects.equals(this.minCosignatories, multisigInfo.minCosignatories);
  }

  /* (non-Javadoc)
   * @see java.lang.Object#hashCode()
   */
  @Override
  public int hashCode() {
    return Objects.hash(cosignatoriesCount, minCosignatories);
  }


  /* (non-Javadoc)
   * @see java.lang.Object#toString()
   */
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MultisigInfo {\n");
    
    sb.append("    cosignatoriesCount: ").append(toIndentedString(cosignatoriesCount)).append("\n");
    sb.append("    minCosignatories: ").append(toIndentedString(minCosignatories)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   *
   * @param o the o
   * @return the string
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

