/*
 * Proximax P2P Storage REST API
 * Proximax P2P Storage REST API
 *
 * OpenAPI spec version: v0.0.1
 * Contact: alvin.reyes@botmill.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.nem.xpx.service.intf;

import io.nem.xpx.exceptions.ApiException;

import java.io.IOException;
import java.security.NoSuchAlgorithmException;

/**
 * The Interface UploadApi.
 */
public interface UploadApi {
	

	/**
	 * Cleanup pinned content using POST.
	 *
	 * @param multihash the multihash
	 * @return the string
	 * @throws ApiException the api exception
	 * @throws IOException Signals that an I/O exception has occurred.
	 */
	String deletePinnedContent(String multihash) throws ApiException, IOException;



	/**
	 * Upload bytes binary.
	 *
	 * @param binaryData the binary data
	 * @param name the name
	 * @param contentType the content type
	 * @param keywords the keywords
	 * @param metadata the metadata
	 * @return the byte[]
	 * @throws ApiException the api exception
	 * @throws IOException Signals that an I/O exception has occurred.
	 * @throws NoSuchAlgorithmException the no such algorithm exception
	 */
	byte[] uploadBytesBinary(byte[] binaryData, String name, String contentType, String keywords, String metadata)
			throws ApiException, IOException, NoSuchAlgorithmException;


	/**
	 * Upload text.
	 *
	 * @param textInBytes the text in bytes
	 * @param name the name
	 * @param contentType the content type
	 * @param encoding the encoding
	 * @param keywords the keywords
	 * @param metadata the metadata
	 * @return the byte[]
	 * @throws ApiException the api exception
	 * @throws IOException Signals that an I/O exception has occurred.
	 * @throws NoSuchAlgorithmException the no such algorithm exception
	 */
	byte[] uploadText(byte[] textInBytes, String name, String contentType, String encoding, String keywords, String metadata)
			throws ApiException, IOException, NoSuchAlgorithmException;


	/**
	 * Upload path.
	 *
	 * @param path the path
	 * @param name the name
	 * @param keywords the keywords
	 * @param metadata the metadata
	 * @return the byte[]
	 * @throws ApiException the api exception
	 * @throws IOException Signals that an I/O exception has occurred.
	 * @throws NoSuchAlgorithmException the no such algorithm exception
	 */
	byte[] uploadPath(String path, String name, String keywords, String metadata)
			throws ApiException, IOException, NoSuchAlgorithmException;
	
}
