/*
 * Proximax P2P Storage REST API
 * Proximax P2P Storage REST API
 *
 * OpenAPI spec version: v0.0.1
 * Contact: alvin.reyes@botmill.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.nem.xpx.intf;

import java.io.IOException;
import java.util.concurrent.ExecutionException;

import io.nem.ApiException;

public interface DownloadApi {
	/**
	 * Download stream using hash using POST.
	 *
	 * @param hash the hash
	 * @return the byte[]
	 * @throws ApiException the api exception
	 * @throws IOException Signals that an I/O exception has occurred.
	 */
	public byte[] downloadUsingDataHashUsingGET(String hash) throws ApiException,IOException;
	public byte[] downloadBinaryUsingGET(String nemHash, String transferMode) throws ApiException, IOException, InterruptedException, ExecutionException;
	public byte[] downloadFileUsingGET(String nemHash, String transferMode) throws ApiException,IOException,InterruptedException, ExecutionException;
	public byte[] downloadTextUsingGET(String nemHash, String transferMode) throws ApiException,IOException,InterruptedException, ExecutionException;
}
