/*
 * Proximax P2P Storage REST API
 * Proximax P2P Storage REST API
 *
 * OpenAPI spec version: v0.0.1
 * Contact: alvin.reyes@botmill.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.nem.xpx.intf;

import java.io.File;
import java.io.IOException;
import java.security.NoSuchAlgorithmException;

import io.nem.api.ApiException;

/**
 * The Interface UploadApi.
 */
public interface PubSubApi {
	
	
	
}
