/*
 * Proximax P2P Storage REST API
 * Proximax P2P Storage REST API
 *
 * OpenAPI spec version: v0.0.1
 * Contact: alvin.reyes@botmill.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.nem.xpx;

import io.ipfs.multihash.Multihash;
import io.nem.ApiCallback;
import io.nem.ApiClient;
import io.nem.ApiException;
import io.nem.ApiResponse;
import io.nem.Configuration;
import io.nem.Pair;
import io.nem.ProgressRequestBody;
import io.nem.ProgressResponseBody;
import io.nem.builder.XpxJavaSdkGlobals;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import io.nem.xpx.model.ResponseEntity;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class LocalDownloadApi implements DownloadApiInterface {
    @Override
    public byte[] downloadStreamUsingHashUsingPOST(String hash) throws ApiException, IOException {
    	return XpxJavaSdkGlobals.getProximaxConnection().cat(Multihash.fromBase58(hash));
    }
}
