/*
 * Proximax P2P Storage REST API
 * Proximax P2P Storage REST API
 *
 * OpenAPI spec version: v0.0.1
 * Contact: alvin.reyes@botmill.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.nem.xpx.service.local;

import io.ipfs.api.IPFS;
import io.ipfs.multihash.Multihash;
import io.nem.xpx.exceptions.ApiException;
import io.nem.xpx.service.intf.DownloadApi;

import java.io.IOException;





/**
 * The Class LocalFuseDownloadApi.
 */
public class LocalFuseDownloadApi implements DownloadApi {

	/** The proximax ifps connection. */
	private final IPFS proximaxIfpsConnection;

	/**
	 * Instantiates a new local fuse download api.
	 *
	 * @param proximaxIfpsConnection the proximax ifps connection
	 */
	public LocalFuseDownloadApi(final IPFS proximaxIfpsConnection) {
		this.proximaxIfpsConnection = proximaxIfpsConnection;
	}

	/* (non-Javadoc)
	 * @see io.nem.xpx.service.intf.DownloadApi#downloadUsingDataHashUsingGET(java.lang.String)
	 */
	@Override
	public byte[] downloadUsingDataHashUsingGET(String hash) throws ApiException, IOException {
		return proximaxIfpsConnection.cat(Multihash.fromBase58(hash));
	}

	/* (non-Javadoc)
	 * @see io.nem.xpx.service.intf.DownloadApi#downloadBinaryUsingGET(java.lang.String, java.lang.String)
	 */
	@Override
	public byte[] downloadBinaryUsingGET(String nemHash, String transferMode) throws ApiException, IOException {
		// TODO Auto-generated method stub
		return null;
	}

	/* (non-Javadoc)
	 * @see io.nem.xpx.service.intf.DownloadApi#downloadFileUsingGET(java.lang.String, java.lang.String)
	 */
	@Override
	public byte[] downloadFileUsingGET(String nemHash, String transferMode) throws ApiException, IOException {
		// TODO Auto-generated method stub
		return null;
	}

	/* (non-Javadoc)
	 * @see io.nem.xpx.service.intf.DownloadApi#downloadTextUsingGET(java.lang.String, java.lang.String)
	 */
	@Override
	public byte[] downloadTextUsingGET(String nemHash, String transferMode) throws ApiException, IOException {
		// TODO Auto-generated method stub
		return null;
	}
	
}
