/*
 * Proximax P2P Storage REST API
 * Proximax P2P Storage REST API
 *
 * OpenAPI spec version: v0.0.1
 * Contact: alvin.reyes@botmill.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.nem.xpx.service.local;

import io.ipfs.multihash.Multihash;
import io.nem.Configuration;
import io.nem.Pair;
import io.nem.ProgressRequestBody;
import io.nem.ProgressResponseBody;
import io.nem.ApiCallback;
import io.nem.ApiClient;
import io.nem.ApiException;
import io.nem.ApiResponse;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;

import io.nem.xpx.service.intf.DownloadApi;
import io.nem.xpx.service.model.ResponseEntity;
import io.nem.xpx.service.model.XpxSdkGlobalConstants;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * The Class LocalFuseDownloadApi.
 */
public class LocalFuseDownloadApi implements DownloadApi {

	@Override
	public byte[] downloadUsingDataHashUsingGET(String hash) throws ApiException, IOException {
		return XpxSdkGlobalConstants.getProximaxConnection().cat(Multihash.fromBase58(hash));
	}

	@Override
	public byte[] downloadBinaryUsingGET(String nemHash, String transferMode) throws ApiException, IOException {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public byte[] downloadFileUsingGET(String nemHash, String transferMode) throws ApiException, IOException {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public byte[] downloadTextUsingGET(String nemHash, String transferMode) throws ApiException, IOException {
		// TODO Auto-generated method stub
		return null;
	}
	
}
