/*
 * Proximax P2P Storage REST API
 * Proximax P2P Storage REST API
 *
 * OpenAPI spec version: v0.0.1
 * Contact: proximax.storage@proximax.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.nem.xpx.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;


/**
 * Amount.
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-04-25T23:45:59.064-04:00")
public class Amount {
  
  /** The num micro nem. */
  @SerializedName("numMicroNem")
  private Long numMicroNem = null;

  /** The num nem. */
  @SerializedName("numNem")
  private Long numNem = null;

  /**
   * Num micro nem.
   *
   * @param numMicroNem the num micro nem
   * @return the amount
   */
  public Amount numMicroNem(Long numMicroNem) {
    this.numMicroNem = numMicroNem;
    return this;
  }

   /**
    * Get numMicroNem.
    *
    * @return numMicroNem
    */
  @ApiModelProperty(value = "")
  public Long getNumMicroNem() {
    return numMicroNem;
  }

  /**
   * Sets the num micro nem.
   *
   * @param numMicroNem the new num micro nem
   */
  public void setNumMicroNem(Long numMicroNem) {
    this.numMicroNem = numMicroNem;
  }

  /**
   * Num nem.
   *
   * @param numNem the num nem
   * @return the amount
   */
  public Amount numNem(Long numNem) {
    this.numNem = numNem;
    return this;
  }

   /**
    * Get numNem.
    *
    * @return numNem
    */
  @ApiModelProperty(value = "")
  public Long getNumNem() {
    return numNem;
  }

  /**
   * Sets the num nem.
   *
   * @param numNem the new num nem
   */
  public void setNumNem(Long numNem) {
    this.numNem = numNem;
  }


  /* (non-Javadoc)
   * @see java.lang.Object#equals(java.lang.Object)
   */
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Amount amount = (Amount) o;
    return Objects.equals(this.numMicroNem, amount.numMicroNem) &&
        Objects.equals(this.numNem, amount.numNem);
  }

  /* (non-Javadoc)
   * @see java.lang.Object#hashCode()
   */
  @Override
  public int hashCode() {
    return Objects.hash(numMicroNem, numNem);
  }


  /* (non-Javadoc)
   * @see java.lang.Object#toString()
   */
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Amount {\n");
    
    sb.append("    numMicroNem: ").append(toIndentedString(numMicroNem)).append("\n");
    sb.append("    numNem: ").append(toIndentedString(numNem)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   *
   * @param o the o
   * @return the string
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

