/*
 * Copyright 2018 ProximaX Limited
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * Proximax P2P Storage REST API
 * Proximax P2P Storage REST API
 *
 * OpenAPI spec version: v0.0.1
 * Contact: proximax.storage@proximax.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.proximax.xpx.local;

import io.proximax.xpx.exceptions.ApiException;
import io.proximax.xpx.remote.AbstractApiTest;
import io.proximax.xpx.service.remote.RemotePublishAndSubscribeApi;
import org.junit.Ignore;
import org.junit.Test;



/**
 * API tests for PublishAndSubscribeApi.
 */
@Ignore
public class LocalPublishAndSubscribeApiTest extends AbstractApiTest{

    /** The api. */
    private final RemotePublishAndSubscribeApi api = new RemotePublishAndSubscribeApi(apiClient);

    
    /**
     * Publish and Subscribe. Make sure that the IPFS daemon has pubsub enabled.
     *
     * Publish and Subscribe. Make sure that the IPFS daemon has pubsub enabled.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void publishTopicUsingGETTest() throws ApiException {
        String topic = null;
        String message = null;
        Object response = api.publishTopicUsingGET(topic, message);

        // TODO: test validations
    }
    
}
