/*
 * Proximax REST API
 * Proximax REST API
 *
 * OpenAPI spec version: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.nem.xpx;

import io.nem.ApiClient;
import io.nem.ApiException;
import io.nem.xpx.model.AccountMetaDataPair;
import org.junit.Test;

/**
 * API tests for AccountApi
 */
public class AccountApiTest {
	
    private final AccountApi api = new AccountApi(new ApiClient().setBasePath("http://p2ptest.smartproof.io/xpxstest1"));

    
    /**
     * getAllIncomingNemAddressTransactions
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllIncomingNemAddressTransactionsUsingGETTest() throws ApiException {
        String publicKey = null;
        String response = api.getAllIncomingNemAddressTransactionsUsingGET(publicKey);

        // TODO: test validations
    }
    
    /**
     * getAllNemAddressTransactions
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllNemAddressTransactionsUsingGETTest() throws ApiException {
        String publicKey = null;
        String response = api.getAllNemAddressTransactionsUsingGET(publicKey);

        // TODO: test validations
    }
    
    /**
     * getAllNemAddressTransactionsWithPageSize
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllNemAddressTransactionsWithPageSizeUsingGETTest() throws ApiException {
        String publicKey = null;
        String pageSize = null;
        String response = api.getAllNemAddressTransactionsWithPageSizeUsingGET(publicKey, pageSize);

        // TODO: test validations
    }
    
    /**
     * getAllOutgoingNemAddressTransactions
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllOutgoingNemAddressTransactionsUsingGETTest() throws ApiException {
        String publicKey = null;
        String response = api.getAllOutgoingNemAddressTransactionsUsingGET(publicKey);

        // TODO: test validations
    }
    
    /**
     * getAllUnconfirmedNemAddressTransactions
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllUnconfirmedNemAddressTransactionsUsingGETTest() throws ApiException {
        String publicKey = null;
        String response = api.getAllUnconfirmedNemAddressTransactionsUsingGET(publicKey);

        // TODO: test validations
    }
    
    /**
     * Get the NEM Address Details
     *
     * This endpoint returns the NEM Address/Account Information of a given address
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getNemAddressDetailsUsingGETTest() throws ApiException {
        String publicKey = null;
        AccountMetaDataPair response = api.getNemAddressDetailsUsingGET(publicKey);

        // TODO: test validations
    }
    
}
