/*
 * Proximax REST API
 * Proximax REST API
 *
 * OpenAPI spec version: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.nem.xpx;

import io.nem.ApiException;
import java.io.File;
import io.nem.xpx.model.RequestAnnounceDataSignature;
import io.nem.xpx.model.ResponseEntity;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PublishAndAnnounceApi
 */
@Ignore
public class PublishAndAnnounceApiTest {

    private final PublishAndAnnounceApi api = new PublishAndAnnounceApi();

    
    /**
     * Announce the DataHash to NEM/P2P Storage and P2P Database
     *
     * Endpoint that can be use to announce the data hash transaction. This will grab the signed BinaryTransaferTransaction and create the P2P Database Entry for the specific data hash / transaction.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void announceRequestPublishDataSignatureUsingPOSTTest() throws ApiException {
        RequestAnnounceDataSignature requestAnnounceDataSignature = null;
        String response = api.announceRequestPublishDataSignatureUsingPOST(requestAnnounceDataSignature);

        // TODO: test validations
    }
    
    /**
     * Store a single file that can only be access by the given address
     *
     * This endpoint can be used to share a file to a specific address only.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void publishAndSendSingleFileToAddressUsingPOSTTest() throws ApiException {
        String xPvkey = null;
        String address = null;
        String messageType = null;
        File file = null;
        String response = api.publishAndSendSingleFileToAddressUsingPOST(xPvkey, address, messageType, file);

        // TODO: test validations
    }
    
    /**
     * Store a single file that can only be access by the given addresses
     *
     * This endpoint can be used to exclusively share files across a set of given addresses. This means that the file that&#39;s published here can only be viewed or downloaded by the given addresses including the uploader.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void publishAndSendSingleFileToAddressesUsingPOSTTest() throws ApiException {
        String xPvkey = null;
        List<String> addresses = null;
        String messageType = null;
        File file = null;
        String response = api.publishAndSendSingleFileToAddressesUsingPOST(xPvkey, addresses, messageType, file);

        // TODO: test validations
    }
    
}
